on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant permissions for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run Tests
        run: ./gradlew clean test

      - name: Generate Version
        id: version
        run: |
          VERSION="v${{ github.run_number }}-$(echo ${{ github.sha }} | cut -c1-7)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

